require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NodePathsController do

  # This should return the minimal set of attributes required to create a valid
  # NodePath. As you add validations to NodePath, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NodePathsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all node_paths as @node_paths" do
      node_path = NodePath.create! valid_attributes
      get :index, {}, valid_session
      assigns(:node_paths).should eq([node_path])
    end
  end

  describe "GET show" do
    it "assigns the requested node_path as @node_path" do
      node_path = NodePath.create! valid_attributes
      get :show, {:id => node_path.to_param}, valid_session
      assigns(:node_path).should eq(node_path)
    end
  end

  describe "GET new" do
    it "assigns a new node_path as @node_path" do
      get :new, {}, valid_session
      assigns(:node_path).should be_a_new(NodePath)
    end
  end

  describe "GET edit" do
    it "assigns the requested node_path as @node_path" do
      node_path = NodePath.create! valid_attributes
      get :edit, {:id => node_path.to_param}, valid_session
      assigns(:node_path).should eq(node_path)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NodePath" do
        expect {
          post :create, {:node_path => valid_attributes}, valid_session
        }.to change(NodePath, :count).by(1)
      end

      it "assigns a newly created node_path as @node_path" do
        post :create, {:node_path => valid_attributes}, valid_session
        assigns(:node_path).should be_a(NodePath)
        assigns(:node_path).should be_persisted
      end

      it "redirects to the created node_path" do
        post :create, {:node_path => valid_attributes}, valid_session
        response.should redirect_to(NodePath.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved node_path as @node_path" do
        # Trigger the behavior that occurs when invalid params are submitted
        NodePath.any_instance.stub(:save).and_return(false)
        post :create, {:node_path => {}}, valid_session
        assigns(:node_path).should be_a_new(NodePath)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NodePath.any_instance.stub(:save).and_return(false)
        post :create, {:node_path => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested node_path" do
        node_path = NodePath.create! valid_attributes
        # Assuming there are no other node_paths in the database, this
        # specifies that the NodePath created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NodePath.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => node_path.to_param, :node_path => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested node_path as @node_path" do
        node_path = NodePath.create! valid_attributes
        put :update, {:id => node_path.to_param, :node_path => valid_attributes}, valid_session
        assigns(:node_path).should eq(node_path)
      end

      it "redirects to the node_path" do
        node_path = NodePath.create! valid_attributes
        put :update, {:id => node_path.to_param, :node_path => valid_attributes}, valid_session
        response.should redirect_to(node_path)
      end
    end

    describe "with invalid params" do
      it "assigns the node_path as @node_path" do
        node_path = NodePath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NodePath.any_instance.stub(:save).and_return(false)
        put :update, {:id => node_path.to_param, :node_path => {}}, valid_session
        assigns(:node_path).should eq(node_path)
      end

      it "re-renders the 'edit' template" do
        node_path = NodePath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NodePath.any_instance.stub(:save).and_return(false)
        put :update, {:id => node_path.to_param, :node_path => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested node_path" do
      node_path = NodePath.create! valid_attributes
      expect {
        delete :destroy, {:id => node_path.to_param}, valid_session
      }.to change(NodePath, :count).by(-1)
    end

    it "redirects to the node_paths list" do
      node_path = NodePath.create! valid_attributes
      delete :destroy, {:id => node_path.to_param}, valid_session
      response.should redirect_to(node_paths_url)
    end
  end

end
